- name: install satellite
  package:
    name: "{{ satellite_packages }}"
    state: present
  become: true

- name: upload answers file
  template:
    src: satellite-answers.yaml
    dest: "{{ satellite_answers_file_destination }}"
    owner: root
    group: root
    mode: 0600
  become: true
  notify: run satellite installer

- name: upload scenario file
  template:
    src: satellite.yaml
    dest: "{{ satellite_scenario_location }}"
    owner: root
    group: root
    mode: 0600
  become: true
  notify: run satellite installer

- name: run installer if necessary
  meta: flush_handlers
