---
# TASKS
- name: patch | Patch yum-clean-metadata
  command: yum clean all
  args:
    warn: no

- name: patch | Remove unneeded packages
  package:
    name: iwl7265-firmware
    state: absent

- name: patch | installing secuity Packages
  package:
    name:
      - screen
      - unzip
      - ipa-client
      - tmux
    state: present

- name: patch | Check if update is required
  shell: yum -q check-update > /dev/null
  register: patch_lvl
  failed_when: patch_lvl.rc not in [100,0]
  become: yes

- name:
  block:
  - name: patch | Patch the system
    package:
      name: "*"
      state: latest

  - name: patch | Reboot on new kernel
    reboot:

  - name: patch | Wait 600 seconds for target connection to become reachable/usable
    wait_for_connection:

  when: patch_lvl.rc == 100

- name: patch | Refreshing Ansible facts
  setup:
