dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-satellite
    image: rhel-7.5-server-x86_64-updated
    flavor: m1.xlarge
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    # Add a -v so you see the individual test names,
    # particularly useful with parameterized tests
    v: true
    junit-xml: junit.xml
  lint:
    name: flake8
